name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  flutter_native_splash: ^2.4.1
  intl: ^0.18.1
  supabase_flutter: ^2.6.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  english_words: ^4.0.0
  flutter_animate: ^4.5.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/exercise.mp3
    - assets/video/exercise.mp4
    - assets/images/splash.png
    - assets/images/select_image.png

flutter_native_splash:
  color: "#add8e6"
  image: "assets/images/splash.png"
  color_dark: "#262626"
  image_dark: "assets/images/splash.png"
  fullscreen: true
  android_12:
    icon_background_color: "#add8e6"
    image: "assets/images/splash_android12.png"
    icon_background_color_dark: "#262626"
    image_dark: "assets/images/splash_android12.png"
